require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SerietreinosController do

  # This should return the minimal set of attributes required to create a valid
  # Serietreino. As you add validations to Serietreino, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "quantidade" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SerietreinosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all serietreinos as @serietreinos" do
      serietreino = Serietreino.create! valid_attributes
      get :index, {}, valid_session
      assigns(:serietreinos).should eq([serietreino])
    end
  end

  describe "GET show" do
    it "assigns the requested serietreino as @serietreino" do
      serietreino = Serietreino.create! valid_attributes
      get :show, {:id => serietreino.to_param}, valid_session
      assigns(:serietreino).should eq(serietreino)
    end
  end

  describe "GET new" do
    it "assigns a new serietreino as @serietreino" do
      get :new, {}, valid_session
      assigns(:serietreino).should be_a_new(Serietreino)
    end
  end

  describe "GET edit" do
    it "assigns the requested serietreino as @serietreino" do
      serietreino = Serietreino.create! valid_attributes
      get :edit, {:id => serietreino.to_param}, valid_session
      assigns(:serietreino).should eq(serietreino)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Serietreino" do
        expect {
          post :create, {:serietreino => valid_attributes}, valid_session
        }.to change(Serietreino, :count).by(1)
      end

      it "assigns a newly created serietreino as @serietreino" do
        post :create, {:serietreino => valid_attributes}, valid_session
        assigns(:serietreino).should be_a(Serietreino)
        assigns(:serietreino).should be_persisted
      end

      it "redirects to the created serietreino" do
        post :create, {:serietreino => valid_attributes}, valid_session
        response.should redirect_to(Serietreino.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved serietreino as @serietreino" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serietreino.any_instance.stub(:save).and_return(false)
        post :create, {:serietreino => { "quantidade" => "invalid value" }}, valid_session
        assigns(:serietreino).should be_a_new(Serietreino)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serietreino.any_instance.stub(:save).and_return(false)
        post :create, {:serietreino => { "quantidade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested serietreino" do
        serietreino = Serietreino.create! valid_attributes
        # Assuming there are no other serietreinos in the database, this
        # specifies that the Serietreino created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Serietreino.any_instance.should_receive(:update_attributes).with({ "quantidade" => "1" })
        put :update, {:id => serietreino.to_param, :serietreino => { "quantidade" => "1" }}, valid_session
      end

      it "assigns the requested serietreino as @serietreino" do
        serietreino = Serietreino.create! valid_attributes
        put :update, {:id => serietreino.to_param, :serietreino => valid_attributes}, valid_session
        assigns(:serietreino).should eq(serietreino)
      end

      it "redirects to the serietreino" do
        serietreino = Serietreino.create! valid_attributes
        put :update, {:id => serietreino.to_param, :serietreino => valid_attributes}, valid_session
        response.should redirect_to(serietreino)
      end
    end

    describe "with invalid params" do
      it "assigns the serietreino as @serietreino" do
        serietreino = Serietreino.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serietreino.any_instance.stub(:save).and_return(false)
        put :update, {:id => serietreino.to_param, :serietreino => { "quantidade" => "invalid value" }}, valid_session
        assigns(:serietreino).should eq(serietreino)
      end

      it "re-renders the 'edit' template" do
        serietreino = Serietreino.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serietreino.any_instance.stub(:save).and_return(false)
        put :update, {:id => serietreino.to_param, :serietreino => { "quantidade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested serietreino" do
      serietreino = Serietreino.create! valid_attributes
      expect {
        delete :destroy, {:id => serietreino.to_param}, valid_session
      }.to change(Serietreino, :count).by(-1)
    end

    it "redirects to the serietreinos list" do
      serietreino = Serietreino.create! valid_attributes
      delete :destroy, {:id => serietreino.to_param}, valid_session
      response.should redirect_to(serietreinos_url)
    end
  end

end
